// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/archive/devices": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archive"
                ],
                "summary": "Archive devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/archive.DeviceSummary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/archive/health": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archive"
                ],
                "summary": "Archive health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/archive.Health"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/archive/integrity": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archive"
                ],
                "summary": "Archive integrity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/archive.IntegrityResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/archive/repositories": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archive"
                ],
                "summary": "Archive repositories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of repositories",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/archive.RepositorySummary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/archive/status": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Archive"
                ],
                "summary": "Archive status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/archive.Status"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.StatusResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/exports/sessions": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json",
                    "text/csv",
                    "text/markdown"
                ],
                "tags": [
                    "Exports"
                ],
                "summary": "Export sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Export format: csv, json, or markdown",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of rows",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort key",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Branch filter",
                        "name": "branch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Text search query",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sessions.ListItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/filter-options": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filter Options"
                ],
                "summary": "Filter options",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/filteroptions.Result"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/ingest/sessions": {
            "post": {
                "security": [
                    {
                        "DeviceTokenAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ingest"
                ],
                "summary": "Ingest sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JSON-encoded ingest metadata array",
                        "name": "metadata",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Raw JSONL file",
                        "name": "raw_0",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/ingest.BatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/projects": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Projects"
                ],
                "summary": "List projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/projects.ProjectSummary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/repositories": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Projects"
                ],
                "summary": "List repositories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/projects.RepositorySummary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/search": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Text search query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of rows",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Set false to skip total count",
                        "name": "includeTotal",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search kind filter",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/search.SearchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sessions": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "List sessions with totals",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of rows",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort key",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Branch filter",
                        "name": "branch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Text search query",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sessions.ListResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sessions/compact": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "List compact sessions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of rows",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort key",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Branch filter",
                        "name": "branch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Text search query",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sessions.SimpleSession"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Session detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sessions.DetailResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}/export": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json",
                    "text/markdown",
                    "application/octet-stream"
                ],
                "tags": [
                    "Exports"
                ],
                "summary": "Export session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Export format: raw, json, or markdown",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}/reader": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Session reader",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of turns",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Text search query",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sessions.ReaderResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}/timeline": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Session timeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of timeline rows",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Timeline kind filter",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Text search query",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sessions.TimelineResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/usage/breakdown": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usage"
                ],
                "summary": "Usage breakdown",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Grouping key: model, repository, project, device, or language",
                        "name": "groupBy",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of rows",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usage.BreakdownItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/usage/calendar": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usage"
                ],
                "summary": "Usage calendar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of days to include",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usage.CalendarDay"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/usage/series": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usage"
                ],
                "summary": "Usage series",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bucket size: day, week, or month",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usage.SeriesBucket"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/usage/summary": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usage"
                ],
                "summary": "Usage summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device ID filter",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Repository ID filter",
                        "name": "repositoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project ID filter",
                        "name": "projectId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Model filter",
                        "name": "model",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usage.Summary"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/usage/totals": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usage"
                ],
                "summary": "Global usage totals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usage.GlobalTotals"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/usage/windows": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usage"
                ],
                "summary": "Recent usage windows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usage.Window"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "archive.DeviceSummary": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastIngestedAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rawBytes": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                }
            }
        },
        "archive.Health": {
            "type": "object",
            "properties": {
                "archiveRows": {
                    "type": "integer"
                },
                "conversationTurns": {
                    "type": "integer"
                },
                "defaultSearchDocs": {
                    "type": "integer"
                },
                "latestIngestedAt": {
                    "type": "string"
                },
                "messages": {
                    "type": "integer"
                },
                "missingArchiveRows": {
                    "type": "integer"
                },
                "missingRawFiles": {
                    "type": "integer"
                },
                "oldestIngestedAt": {
                    "type": "string"
                },
                "searchDocuments": {
                    "type": "integer"
                },
                "sessionSummaries": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "toolEvents": {
                    "type": "integer"
                },
                "verifiedArchiveRows": {
                    "type": "integer"
                }
            }
        },
        "archive.IntegrityIssue": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "problem": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "archive.IntegrityResult": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "integer"
                },
                "issues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/archive.IntegrityIssue"
                    }
                },
                "missingFile": {
                    "type": "integer"
                },
                "missingPath": {
                    "type": "integer"
                },
                "missingSha": {
                    "type": "integer"
                },
                "ok": {
                    "type": "integer"
                },
                "sizeMismatch": {
                    "type": "integer"
                }
            }
        },
        "archive.RepositorySummary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "lastIngestedAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rawBytes": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "archive.Status": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "integer"
                },
                "messages": {
                    "type": "integer"
                },
                "missingRawFiles": {
                    "type": "integer"
                },
                "missingRawSha": {
                    "type": "integer"
                },
                "newestIngestedAt": {
                    "type": "string"
                },
                "newestSessionTime": {
                    "type": "string"
                },
                "oldestIngestedAt": {
                    "type": "string"
                },
                "oldestSessionTime": {
                    "type": "string"
                },
                "rawBytes": {
                    "type": "integer"
                },
                "sessionEvents": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                },
                "toolEvents": {
                    "type": "integer"
                },
                "usageEvents": {
                    "type": "integer"
                }
            }
        },
        "filteroptions.DateRange": {
            "type": "object",
            "properties": {
                "newest": {
                    "type": "string"
                },
                "oldest": {
                    "type": "string"
                }
            }
        },
        "filteroptions.Option": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "detail": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "filteroptions.Result": {
            "type": "object",
            "properties": {
                "branches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/filteroptions.Option"
                    }
                },
                "dateRange": {
                    "$ref": "#/definitions/filteroptions.DateRange"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/filteroptions.Option"
                    }
                },
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/filteroptions.Option"
                    }
                },
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/filteroptions.Option"
                    }
                },
                "repositories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/filteroptions.Option"
                    }
                }
            }
        },
        "httpapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "httpapi.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "httpapi.MeResponse": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                }
            }
        },
        "httpapi.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "ingest.BatchResponse": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer"
                },
                "ingested": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ingest.ItemResponse"
                    }
                },
                "skipped": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "ingest.ItemResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "raw_file_path": {
                    "type": "string"
                },
                "raw_sha256": {
                    "type": "string"
                },
                "raw_size_bytes": {
                    "type": "integer"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "projects.ProjectSummary": {
            "type": "object",
            "properties": {
                "costUsd": {
                    "type": "number"
                },
                "cwd": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "relativePath": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                },
                "repositoryUrl": {
                    "type": "string"
                },
                "sessions": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "projects.RepositorySummary": {
            "type": "object",
            "properties": {
                "costUsd": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "repositoryUrl": {
                    "type": "string"
                },
                "sessions": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "search.Result": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "cwd": {
                    "type": "string"
                },
                "defaultSearchable": {
                    "type": "boolean"
                },
                "documentScope": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "matchEnd": {
                    "type": "integer"
                },
                "matchStart": {
                    "type": "integer"
                },
                "occurredAt": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                },
                "rankWeight": {
                    "type": "integer"
                },
                "repository": {
                    "type": "string"
                },
                "repositoryUrl": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "sessionId": {
                    "type": "string"
                },
                "sessionSummary": {
                    "type": "string"
                },
                "sessionTitle": {
                    "type": "string"
                },
                "snippet": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "toolName": {
                    "type": "string"
                },
                "turnIndex": {
                    "type": "integer"
                }
            }
        },
        "search.SearchResult": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.Result"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "nextOffset": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalKnown": {
                    "type": "boolean"
                }
            }
        },
        "sessions.Detail": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "cacheHitRate": {
                    "type": "number"
                },
                "cachedInputTokens": {
                    "type": "integer"
                },
                "commitHash": {
                    "type": "string"
                },
                "conversationTurns": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "cwd": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "displaySubtitle": {
                    "type": "string"
                },
                "displayTitle": {
                    "type": "string"
                },
                "dominantLanguage": {
                    "type": "string"
                },
                "durationSeconds": {
                    "type": "integer"
                },
                "firstUserMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "lastUserMessage": {
                    "type": "string"
                },
                "mainModel": {
                    "type": "string"
                },
                "messageCount": {
                    "type": "integer"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "patchAddedLines": {
                    "type": "integer"
                },
                "project": {
                    "type": "string"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "repository": {
                    "type": "string"
                },
                "repositoryUrl": {
                    "type": "string"
                },
                "searchableMessages": {
                    "type": "integer"
                },
                "searchableTools": {
                    "type": "integer"
                },
                "shortSummary": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "toolCallCount": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userIntent": {
                    "type": "string"
                }
            }
        },
        "sessions.DetailResult": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sessions.ModelUsage"
                    }
                },
                "session": {
                    "$ref": "#/definitions/sessions.Detail"
                },
                "timeline": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "sessions.ListItem": {
            "type": "object",
            "properties": {
                "assistantMessageCount": {
                    "type": "integer"
                },
                "branch": {
                    "type": "string"
                },
                "cacheHitRate": {
                    "type": "number"
                },
                "cachedInputTokens": {
                    "type": "integer"
                },
                "conversationTurns": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "cwd": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "displaySubtitle": {
                    "type": "string"
                },
                "displayTitle": {
                    "type": "string"
                },
                "dominantLanguage": {
                    "type": "string"
                },
                "durationSeconds": {
                    "type": "integer"
                },
                "firstUserMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "lastUserMessage": {
                    "type": "string"
                },
                "mainModel": {
                    "type": "string"
                },
                "messageCount": {
                    "type": "integer"
                },
                "models": {
                    "type": "string"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "patchAddedLines": {
                    "type": "integer"
                },
                "project": {
                    "type": "string"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "repository": {
                    "type": "string"
                },
                "repositoryUrl": {
                    "type": "string"
                },
                "searchableMessages": {
                    "type": "integer"
                },
                "searchableTools": {
                    "type": "integer"
                },
                "shortSummary": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "toolCallCount": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userIntent": {
                    "type": "string"
                },
                "userMessageCount": {
                    "type": "integer"
                }
            }
        },
        "sessions.ListResult": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sessions.ListItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "nextOffset": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totals": {
                    "$ref": "#/definitions/sessions.UsageTotals"
                }
            }
        },
        "sessions.ModelUsage": {
            "type": "object",
            "properties": {
                "cachedInputTokens": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "sessions.ReaderResult": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sessions.ReaderTurn"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "nextOffset": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "summary": {
                    "$ref": "#/definitions/sessions.ReaderSummary"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "sessions.ReaderSummary": {
            "type": "object",
            "properties": {
                "assistantMessageCount": {
                    "type": "integer"
                },
                "cacheHitRate": {
                    "type": "number"
                },
                "conversationTurnCount": {
                    "type": "integer"
                },
                "displaySubtitle": {
                    "type": "string"
                },
                "displayTitle": {
                    "type": "string"
                },
                "dominantLanguage": {
                    "type": "string"
                },
                "durationSeconds": {
                    "type": "integer"
                },
                "firstUserMessage": {
                    "type": "string"
                },
                "lastUserMessage": {
                    "type": "string"
                },
                "mainModel": {
                    "type": "string"
                },
                "messageCount": {
                    "type": "integer"
                },
                "searchableDocumentRows": {
                    "type": "integer"
                },
                "sessionId": {
                    "type": "string"
                },
                "shortSummary": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "toolCallCount": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userIntent": {
                    "type": "string"
                },
                "userMessageCount": {
                    "type": "integer"
                }
            }
        },
        "sessions.ReaderTurn": {
            "type": "object",
            "properties": {
                "assistantSeq": {
                    "type": "integer"
                },
                "assistantText": {
                    "type": "string"
                },
                "endedAt": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "toolCallCount": {
                    "type": "integer"
                },
                "toolNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "toolResultCount": {
                    "type": "integer"
                },
                "turnIndex": {
                    "type": "integer"
                },
                "userSeq": {
                    "type": "integer"
                },
                "userText": {
                    "type": "string"
                }
            }
        },
        "sessions.SimpleSession": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "cachedInputTokens": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "cwd": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "models": {
                    "type": "string"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "project": {
                    "type": "string"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "repository": {
                    "type": "string"
                },
                "repositoryUrl": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "totalTokens": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "sessions.TimelineItem": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string"
                },
                "occurredAt": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "toolName": {
                    "type": "string"
                }
            }
        },
        "sessions.TimelineResult": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sessions.TimelineItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "nextOffset": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "sessions.UsageTotals": {
            "type": "object",
            "properties": {
                "cachedInputTokens": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "integer"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "patchAddedLines": {
                    "type": "integer"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                },
                "toolCalls": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "usage.BreakdownItem": {
            "type": "object",
            "properties": {
                "cachedInputTokens": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "detail": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "patchAddedLines": {
                    "type": "integer"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "usage.CalendarDay": {
            "type": "object",
            "properties": {
                "costUsd": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "projects": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "usage.GlobalTotals": {
            "type": "object",
            "properties": {
                "costUsd": {
                    "type": "number"
                },
                "devices": {
                    "type": "integer"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "patchAddedLines": {
                    "type": "integer"
                },
                "projects": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "usage.SeriesBucket": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "cachedInputTokens": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "patchAddedLines": {
                    "type": "integer"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "usage.Summary": {
            "type": "object",
            "properties": {
                "activeDays": {
                    "type": "integer"
                },
                "avgSessionCost": {
                    "type": "number"
                },
                "cacheHitRate": {
                    "type": "number"
                },
                "current": {
                    "$ref": "#/definitions/usage.Totals"
                }
            }
        },
        "usage.Totals": {
            "type": "object",
            "properties": {
                "cachedInputTokens": {
                    "type": "integer"
                },
                "costUsd": {
                    "type": "number"
                },
                "inputTokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "integer"
                },
                "outputTokens": {
                    "type": "integer"
                },
                "patchAddedLines": {
                    "type": "integer"
                },
                "reasoningOutputTokens": {
                    "type": "integer"
                },
                "sessions": {
                    "type": "integer"
                },
                "toolCalls": {
                    "type": "integer"
                },
                "totalTokens": {
                    "type": "integer"
                }
            }
        },
        "usage.Window": {
            "type": "object",
            "properties": {
                "cacheHitRate": {
                    "type": "number"
                },
                "days": {
                    "type": "integer"
                },
                "from": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "totals": {
                    "$ref": "#/definitions/usage.Totals"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "Admin session cookie. Login first, then send the codex_usage_session cookie.",
            "type": "apiKey",
            "name": "Cookie",
            "in": "header"
        },
        "DeviceTokenAuth": {
            "description": "Device ingest token. Authorization: Bearer \u003ctoken\u003e is also accepted by the server.",
            "type": "apiKey",
            "name": "X-Device-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "codex-usage API",
	Description:      "API for Codex usage ingestion, session browsing, usage reporting, and archive inspection.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
